- plank: 30
- plank: 30
- plank: 30
- abs_rotate: 30
- abs_rotate: 30
- abs_rotate: 30
- plank_hands_to_shoulders: 30
- plank_hands_to_shoulders: 30
- plank_hands_to_shoulders: 30
- plank_knees_to_hands: 30
- plank_knees_to_hands: 30
- plank_knees_to_hands: 30
- abs_hold_up: 30
- abs_hold_up: 30
- abs_hold_up: 30
- plank_rotate_hands_up: 30
- plank_rotate_hands_up: 30
- plank_rotate_hands_up: 30
- plank_to_dog: 30
- plank_to_dog: 30
- plank_to_dog: 30
- plank: 20
- plank: 20
- plank: 20
- abs_rotate: 20
- abs_rotate: 20
- abs_rotate: 20
- plank_hands_to_shoulders: 20
- plank_hands_to_shoulders: 20
- plank_hands_to_shoulders: 20
- plank_knees_to_hands: 20
- plank_knees_to_hands: 20
- plank_knees_to_hands: 20
- abs_hold_up: 20
- abs_hold_up: 20
- abs_hold_up: 20
- plank_rotate_hands_up: 20
- plank_rotate_hands_up: 20
- plank_rotate_hands_up: 20
- plank_to_dog: 20
- plank_to_dog: 20
- plank_to_dog: 20

